// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRvkSoPoLWIoFZ5rXo_nYDSaULxQjfd8',
    appId: '1:870671774381:web:4876bc92bb39528953cc24',
    messagingSenderId: '870671774381',
    projectId: 'kanban-board-app-4e6e1',
    authDomain: 'kanban-board-app-4e6e1.firebaseapp.com',
    storageBucket: 'kanban-board-app-4e6e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDvOKYFDLMhWZ5gpsJhc2_liY2sglXQ6c',
    appId: '1:870671774381:android:7fbf633b90ee5c2153cc24',
    messagingSenderId: '870671774381',
    projectId: 'kanban-board-app-4e6e1',
    storageBucket: 'kanban-board-app-4e6e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFDXbcDrmX7tHZI0DH6jT3OuRmTNexuac',
    appId: '1:870671774381:ios:2ae98d83cb932ee953cc24',
    messagingSenderId: '870671774381',
    projectId: 'kanban-board-app-4e6e1',
    storageBucket: 'kanban-board-app-4e6e1.firebasestorage.app',
    iosBundleId: 'com.example.kanbanBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFDXbcDrmX7tHZI0DH6jT3OuRmTNexuac',
    appId: '1:870671774381:ios:2ae98d83cb932ee953cc24',
    messagingSenderId: '870671774381',
    projectId: 'kanban-board-app-4e6e1',
    storageBucket: 'kanban-board-app-4e6e1.firebasestorage.app',
    iosBundleId: 'com.example.kanbanBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgRvkSoPoLWIoFZ5rXo_nYDSaULxQjfd8',
    appId: '1:870671774381:web:1eadd9a3274daf8253cc24',
    messagingSenderId: '870671774381',
    projectId: 'kanban-board-app-4e6e1',
    authDomain: 'kanban-board-app-4e6e1.firebaseapp.com',
    storageBucket: 'kanban-board-app-4e6e1.firebasestorage.app',
  );

}